# Generated by Django 5.2.8 on 2025-11-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название прайса')),
                ('file', models.FileField(upload_to='prices/', verbose_name='Файл')),
                ('size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Размер (МБ)')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
