# Generated by Django 5.2.8 on 2025-11-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('retail_outlets', models.CharField(max_length=255, verbose_name='Товырных точек')),
                ('trading_positions', models.CharField(max_length=255, verbose_name='Торговых позицыии')),
                ('image', models.ImageField(upload_to='about', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
