# Generated by Django 5.2.8 on 2025-11-07 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_gallery/', verbose_name='Изображение')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.about', verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'Изображение (О нас)',
                'verbose_name_plural': 'Изображения (О нас)',
            },
        ),
    ]
