# Generated by Django 5.2.8 on 2025-11-07 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_about_image_aboutimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutimage',
            options={},
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='retail_outlets',
            field=models.CharField(max_length=255, verbose_name='Товарных точек'),
        ),
        migrations.AlterField(
            model_name='about',
            name='trading_positions',
            field=models.CharField(max_length=255, verbose_name='Торговых позиций'),
        ),
        migrations.AlterField(
            model_name='aboutimage',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.about'),
        ),
        migrations.AlterField(
            model_name='aboutimage',
            name='image',
            field=models.ImageField(upload_to='about_images/'),
        ),
    ]
