# Generated by Django 5.2.8 on 2025-11-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutimage_options_aboutimage_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
