# Generated by Django 5.2.8 on 2025-11-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brend',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
