# Generated by Django 5.2.8 on 2025-11-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default=1, max_length=50, verbose_name='Размеры'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
