# Generated by Django 5.2.8 on 2025-11-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_category_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prise',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (сом)'),
        ),
    ]
